### ISSUE TITLE
Unable to subscribe to User GitGutter autocmd

### ISSUE THREAD

**Issue by katsika** [tjdevries/express_line.nvim#12]
```lua
subscribe.buf_autocmd(
'el_git_hunks', 'User GitGutter',
function(window, buffer)
  return
end
)
```
Errors with
```
Error detected while processing User Autocommands for "GitGutter":
E488: Trailing characters: <buffer=1> :lua require(
```

(`:h gitgutter-autocommands`)

**Comment by tjdevries** [comment]
Does this commit work for you?

4c601e297a9e341ff0fc75c5872721e3abd6cde0

Thanks.

**Comment by katsika** [comment]
Thanks for looking into it. It doesn't seem to work as expected though, perhaps because of GitGutter itself, but I am not sure.

`User` autocommand gets created as expected: 
```viml
:autocmd User GitGutter
--- Autocommands ---
ElUserSubscriptions  User
    GitGutter :lua require("el.subscribe")._process_buf_callback(1, "1")
Press ENTER or type command to continue
```
`GitGutterGetHunkSummary()` returns `[0,0,0]` on an initial call and never seems to be updated afterwards.

Testing with:

```lua
subscribe.user_autocmd(
'el_git_hunks',
'GitGutter',
function(window, buffer)
  local input = vim.fn.GitGutterGetHunkSummary()
  return table.concat(input, ', ')
end
),
```

**Comment by tjdevries** [comment]
I think I just need to figure out how `User` autocommands work a bit more haha -- I haven't used them in quite awhile (particularly from statusline and potentially not in the current buffer).

**Comment by smartding** [comment]
I personally use the follow function to subscribe to gitgutter event.
Make sure you update express_line because there is an update to user auto command subscription lately:
```lua
local gitgutter_summary = subscribe.user_autocmd(
  "el_gitgutter_summary",
  "GitGutter",
  function(_, buffer)
    local ok, res = pcall(vim.api.nvim_buf_get_var, buffer.bufnr, 'gitgutter')
    if ok then
      -- summary format: { added, modified, removed }
      local summary = res.summary
      return summary and string.format("[+%d ~%d -%d]", summary[1], summary[2], summary[3]) or ''
    else
      return ''
    end
  end
)
```

**Comment by katsika** [comment]
@smartding Thanks for your contribution to el!

I have since moved to gitsigns which provides `b:gitsigns_status` variable and  by @tjdevries's [advice about variables](https://github.com/tjdevries/express_line.nvim/issues/34#issuecomment-724012747) I have removed the need for User auto command.

Have installed `vim-gitgutter` quickly now to retest it and it seems to be working fine now.

**Comment by smartding** [comment]
> @smartding Thanks for your contribution to el!
> 
> I have since moved to gitsigns which provides `b:gitsigns_status` variable and by @tjdevries's [advice about variables](https://github.com/tjdevries/express_line.nvim/issues/34#issuecomment-724012747) I have removed the need for User auto command.
> 
> Have installed `vim-gitgutter` quickly now to retest it and it seems to be working fine now.

There's no need to switch to gitsigns if all you want is a buffer variable. gitgutter has a buffer variable too, as demonstrated in the following function.

Following tj's advice, instead of using user auto commands, we can just use the following function:
```lua
local gitgutter_summary = function(_, buffer)
  local ok, res = pcall(vim.api.nvim_buf_get_var, buffer.bufnr, 'gitgutter')
  if ok then
    -- summary format: { added, modified, removed }
    local summary = res.summary
    return summary and string.format("[+%d ~%d -%d]", summary[1], summary[2], summary[3]) or ''
  else
    return ''
  end
end
```

**Comment by katsika** [comment]
Using something like that atm:

```
git_chunks = function(win, buf)
  if win.width > 80 then
    local ok, res = pcall(a.nvim_buf_get_var, buf.bufnr, "gitsigns_status")
    if ok then
      return #res > 0 and "(" .. res .. ") " or ""
    end
  end
end,
```

gitsigns provides preformatted string, without zero values, which is exactly what I want.
