### ISSUE TITLE
Bug with git extensions and packer.nvim

### ISSUE THREAD

**Issue by delianides** [tjdevries/express_line.nvim#23]
When I use `extensions.git_changes` or `extensions.git_branch` in my status line I get the following errors when I run `PackerUpdate`

```
Error executing vim.schedule lua callback: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:82: Failed to save undo information
Error executing vim.schedule lua callback: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:82: Failed to save undo information
Error executing vim.schedule lua callback: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:130: Expected 4 arguments
```

Specifically it seems like theres an issue in the `j:sync()` call in the function. I'm not sure if the issue is in this plugin or if its in `plenary.job`. If I remove those extensions then everything works fine.

Please let me know if this isn't the right repo to post this. I'm still troubleshooting.

**Comment by tjdevries** [comment]
Ah, I've found the issue. It requires a patch to neovim. I have made the patch, and once it's in, you can try updating nvim and this plugin and its dependencies. 

That should solve the problem. 

Good find!

**Comment by tjdevries** [comment]
OK, I've merged stuff in neovim, plenary and here :laughing: 

If you update your plugins and use latest nvim, I think this issue will go away.

**Comment by delianides** [comment]
Everything's working now. Thanks!
