### ISSUE TITLE
Highlight sections

### ISSUE THREAD

**Issue by tami5** [tjdevries/express_line.nvim#24]
Hi @tjdevries , how are you doing? 

Finally, got the opportunity to try out and setup your awesome suit of plugin with my new neovim configuration from scratch with lua. To be honest, I was a bit hesitant with using `express_line.nvim`, as I was consider a more mature alternative, however after setting it up, wow I fall in love with it, and I was surprise of how much easy to hack it and read the source code. 

I tried looking for a way to highlight section but a field to do so, basically, I want to try and highlight the empty middle section with dark color and keep the right and left section as is. 

My config

```
local bui        = require('el.builtin')
local ext        = require('el.extensions')
local sec        = require('el.sections')
local sub        = require('el.subscribe')
local col        = sec.collapse_builtin
local _space     = ' '
local _separator = ' | '
local _icon      = ext.file_icon
local _file      = bui.shortened_file -- TODO: have [NO NAME] showing if no file name
local _readonly  = col{ _space, bui.readonly_list, } -- TODO: fix the extra space when the read-only is not visible
local _modefied  = col{ _space, bui.modified_flag }
local _filetype  = col{ _separator, bui.filetype_list, _separator}
local _gbranch   = col{ _separator, ext.git_branch}
local _gchanges  = sub.buf_autocmd( "el_git_changes", "BufWritePost", function(window, buffer) return ext.git_changes(window, buffer) end)
local _buflines  = bui.line_with_width(1) .. ',' .. bui.column_with_width(1)
local _bufloc    = bui.percentage_through_window
local _split     = sec.split
local statusline = function()
  return {
    _space, 
    _icon,
    _space,
    _file, 
    _readonly,
    _modefied,
    _split,
    -- _gbranch,
    _filetype,
    _buflines,
    _separator,
    _bufloc,
    _space,
  }
end

local setup = function()
  require('el').setup({ generator = statusline })
end
```

Also, looking forward for your next stream, I'll make sure I get twitch notification this time :D.

**Comment by tjdevries** [comment]
I think you're looking for `sections.highlight`? Does that work for what you're looking for?

Also, really glad you like it :) Very happy to hear.

**Comment by tami5** [comment]
I did try it but for some reason it didn't work for me or I didn't know how to use it. Also, weather it's possible to highlight the whole spectator. Could you please provide an example. Thanks

**Comment by tjdevries** [comment]
OK, you should now be able to `sections.highlight`.

You can do something like `sections.highlight("MyHighlight", item)` or `sections.highlight("MyHighlight", {item1, item2})` I think will both work.

You can re-open this if it doesn't work for you.

**Comment by tami5** [comment]
@tjdevries Thanks a lot
