### ISSUE TITLE
Hide statusline in some buffer types

### ISSUE THREAD

**Issue by tami5** [tjdevries/express_line.nvim#26]
Hey, I want to hide statusline in some buffer types like minimap.

```lua
w.create_augroup('ui_minimap', {'Filetype', 'minimap', [[setlocal statusline=\ ]]})
```

The above works, but as soon I switch to the buffer, express_line takes over and show the statusline.

Thanks

**Comment by smartding** [comment]
The fzf.vim plugin suggests the follow setting to auto hide status line for fzf buffers:
```vim
autocmd! FileType fzf set laststatus=0 noshowmode noruler
  \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler
```

**Comment by tami5** [comment]
Thanks a lot @smartding that solves it.
