### ISSUE TITLE
How to properly call function with argument

### ISSUE THREAD

**Issue by katsika** [tjdevries/express_line.nvim#34]
Trying to make a function accept an argument (other functions work correctly, but neither of them takes an argument apart of `window` and `buffer`). Code below seems to be executed on initial el load only and never updates afterwards.

```lua
local _coc_diag = function(_, buf, severity)
  local ok, res = pcall(vim.api.nvim_buf_get_var, buf.bufnr, 'coc_diagnostic_info' ) -- {'information': 0, 'hint': 0, 'lnums': [29, 13, 0, 0], 'warning': 15, 'error': 2}
​
  if ok then
    return res[severity]
  end
end
​
local statusline = function(window, buffer)
  return {_coc_diag(window, buffer, 'error')}
end
​
require("el").setup({generator = statusline})
```

What am I doing wrong? Thanks!

**Comment by OkanEsen** [comment]
You need to use `subscribe.user_autocmd`, like this:

  ``` lua
subscribe.user_autocmd(
    "el_coc_diagnostic_changes",
    "CocDiagnosticChange",
    function(window, buffer)
      return _coc_diag(window, buffer, "error")
    end
)
```

**Comment by tjdevries** [comment]
```lua
local _coc_diag = function(_, buf, severity)
  local ok, res = pcall(vim.api.nvim_buf_get_var, buf.bufnr, 'coc_diagnostic_info' ) -- {'information': 0, 'hint': 0, 'lnums': [29, 13, 0, 0], 'warning': 15, 'error': 2}
​
  if ok then
    return res[severity]
  end
end
​
local statusline = function(window, buffer)
  return {
    function(window, buffer)
      return _coc_diag(window, buffer, 'error')
    end,
  }
end
​
require("el").setup({generator = statusline})
```

That might work!

**Comment by OkanEsen** [comment]
> ```lua
> local _coc_diag = function(_, buf, severity)
>   local ok, res = pcall(vim.api.nvim_buf_get_var, buf.bufnr, 'coc_diagnostic_info' ) -- {'information': 0, 'hint': 0, 'lnums': [29, 13, 0, 0], 'warning': 15, 'error': 2}
> ​
>   if ok then
>     return res[severity]
>   end
> end
> ​
> local statusline = function(window, buffer)
>   return {
>     function(window, buffer)
>       return _coc_diag(window, buffer, 'error')
>     end,
>   }
> end
> ​
> require("el").setup({generator = statusline})
> ```
> 
> That might work!

Not OP but that does indeed work! I was under the impression, that everything defined inside setup was only for the initial render and any subsequent changes needed a manual "rerender" of some sort.

If you don't mind me asking, could there be any performance hit without going the autocmd road? I'm asking, because the snippet I posted should only be updated as soon as `CocDiagnosticChange` is fired, no? Though I think that both methods shouldn't fire that many updates anyway, so it shouldn't matter at the end, right?

**Comment by katsika** [comment]
@OkanEsen I was thinking exactly the same. Keen to find out about performance difference between autocmd (gain?) and your way, @tjdevries. 

Wasn't aware of that autocmd, really liking what you have posted, @OkanEsen, thanks!

My initial four functions have grown into five. :) Is there a way to streamline it somehow?

```
local _coc_diag = function(_, buf, severity)
  local ok, res = pcall(a.nvim_buf_get_var, buf.bufnr, 'coc_diagnostic_info' )

  if ok then
    local count = res[severity]
    return count > 0 and string.format(' %s%s ', severity:sub(1, 1), count) or ''
  end
end

local coc_error = sub.user_autocmd(
  'el_coc_diagnostic_changes_e',
  'CocDiagnosticChange',
  function(win, buf)
    return _coc_diag(win, buf, 'error')
  end
)
local coc_warning = sub.user_autocmd(
  'el_coc_diagnostic_changes_w',
  'CocDiagnosticChange',
  function(win, buf)
    return _coc_diag(win, buf, 'warning')
  end
)
local coc_hint = sub.user_autocmd(
  'el_coc_diagnostic_changes_h',
  'CocDiagnosticChange',
  function(win, buf)
    return _coc_diag(win, buf, 'hint')
  end
)
local coc_information = sub.user_autocmd(
  'el_coc_diagnostic_changes_i',
  'CocDiagnosticChange',
  function(win, buf)
    return _coc_diag(win, buf, 'information')
  end
)

local statusline = function(window, buffer)
  return {
     hi({active = 'CocListBlackGreen',  inactive = ei}, coc_information),
     hi({active = 'CocListBlackWhite',  inactive = ei}, coc_hint),
     hi({active = 'CocListBlackYellow', inactive = ei}, coc_warning),
     hi({active = 'CocListBlackRed',    inactive = ei}, coc_error)
  }
end
```

Could perhaps avoid `coc_<severity>` functions somehow by something like this?

```
hi({active = 'CocListBlackRed',    inactive = ei}, function(window, buffer) return _coc_diag(window, buffer, 'error') end),
```

Will callback function in `subscribe_autocmd(_, _, func(win, but, severity))` receive that argument?

Also, should only one variable be used to store the result? Does it not store the value returned by callback? I think there should be variable for each severity.

Thanks for your inputs!

**Comment by katsika** [comment]
I have tried something like this

```lua
local _coc_diag = function(buf, severity)
  local ok, res = pcall(a.nvim_buf_get_var, buf.bufnr, 'coc_diagnostic_info' )

  if ok then
    local count = res[severity]

    if count > 0 then
      local prefix = severity:sub(1,1)
    
      return sub.user_autocmd(
        'el_coc_diagnostic_changes_' .. prefix,
         'CocDiagnosticChange',
         string.format(' %s%s ', prefix, count)
      )
    end
  end
end
```

Calling it from generator with
```lua
hi({active = 'CocListBlackRed', inactive = ei}, function(win, buf) return _coc_diag(buf, 'error') end)
```

It prints `function: 0x0d211b70` instead of actual result. What am I doing wrong here?

**Comment by tjdevries** [comment]
I don't think you need to make it so complicated with the autocmds. Looking up buffer local variables is basically "free". In fact, it's basically what I do to check the autocmd stuff. So I think you should just remove the autocmds and call the bufer lookup in the generator.

This is what I mean: https://github.com/tjdevries/express_line.nvim/issues/34#issuecomment-717986807

These are VERY cheap functions, you do not need to worry about the perf. I generally use the autocmds section for doing stuff related to hitting disk, running a job, expensive calculation, etc. You do not need to worry about this :) variable lookups are "free" :)
