### ISSUE TITLE
Showing LSP status

### ISSUE THREAD

**Issue by ludwj61** [tjdevries/express_line.nvim#37]
Using https://github.com/nvim-lua/lsp-status.nvim I have been able to get warnings, error, etc. showing in the default statusline. However, with this plugin, with
```lua
...
local lsp_statusline = require('el.plugins.lsp_status')
...
lsp_statusline.current_function,
lsp_statusline.server_progress,
...
```
in my config, I _only_ see the current function and nothing about server progress, errors, warnings, etc. Is there a way to include that?

**Comment by ludwj61** [comment]
Actually, using ``lsp_statusline.segment`` seems to get me what I was usually seeing from lsp_status, but is there any way to "separate" it into that is given in this plugin, e.g. ``lsp_statusline.current_function``, ``lsp_statusline.server_progress``, etc?

**Comment by smartding** [comment]
You can use the built in `current_function` for current function name.
There's no builtin function for diagnostics,  I personally use the following one:
```lua
local function lsp_diagnostics(window, buffer)
  if not buffer.lsp then return '' end

  local level_indicator = {
    Error = 'E',
    Warning = 'W',
    Information = 'I',
    Hint = 'H'
  }
  local diagnostics_str = ''

  for level, indicator in pairs(level_indicator) do
      local count = vim.lsp.diagnostic.get_count(buffer.bufnr, level)
      if count > 0 then
        diagnostics_str = diagnostics_str .. indicator .. ' ' .. count .. ' '
      end
  end

  if #diagnostics_str > 0 then return '[ ' .. diagnostics_str .. ']' end

  return ''
end
```

**Comment by ludwj61** [comment]
thanks!
