### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rnhmjoj** [tjdevries/express_line.nvim#57]
There is no mention in this repository of the license under which this software is provided.
For my own personal use, I have modified express_line a bit, so I would like to know if I can redistribute the code.

**Comment by tjdevries** [comment]
Yeah, sorry about that. It's MIT, so you can do whatever you like (or feel free to submit PRs and I will try and respond)

**Comment by tjdevries** [comment]
(I have added in latest commit)
