### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by katsika** [tjdevries/express_line.nvim#9]
Amazing statusline, thanks!

There is a problem with aligning center element when line number is double digit and column changes between single and double digit as seen below.

![el](https://user-images.githubusercontent.com/796021/93000380-7645bc00-f528-11ea-9566-7cd07682d1d5.gif)

**Comment by tjdevries** [comment]
Ah, so you want that part to take fixed width? So it's not so noisy?

**Comment by tjdevries** [comment]
You can now do something like this:

```lua
      '[', builtin.line_with_width(3), ':',  builtin.column_with_width(2), ']',
```

To set the width that you want for line and column.

If that works for you, feel free to close the issue.

**Comment by katsika** [comment]
Would you mind adding right alignment as well? It works much better now though.
